<a href="https://colab.research.google.com/github/aabidproo/ConceptsOfAI-2ndyear/blob/main/ConceptofAI_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

empty_array_1 = np.empty((2, 2))
print("Empty array 2x2:\n", empty_array_1)

ones_array = np.ones((4, 2))
print("\nAll-one array 4x2:\n", ones_array)

filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nFilled array 3x3 with 7:\n", filled_array)

sample_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(sample_array)
print("\nZeros like sample_array:\n", zeros_like_array)

ones_like_array = np.ones_like(sample_array)
print("\nOnes like sample_array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from list:\n", array_from_list)

Empty array 2x2:
 [[9.75496566e-316 0.00000000e+000]
 [2.12199579e-314 5.30886346e+180]]

All-one array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like sample_array:
 [[0 0 0]
 [0 0 0]]

Ones like sample_array:
 [[1 1 1]
 [1 1 1]]

Array from list:
 [1 2 3 4]


In [ ]:
arr_10_49 = np.arange(10, 50)
print(arr_10_49)

matrix_0_8 = np.arange(9).reshape(3, 3)
print(matrix_0_8)

identity_3 = np.eye(3)
print(identity_3)

random_30 = np.random.random(30)
mean_val = random_30.mean()
print(mean_val)

rand_10x10 = np.random.random((10, 10))
print(rand_10x10.min(), rand_10x10.max())

zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(border_arr)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.63740436584759
0.00798901049574241 0.9941886412862557
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print(add_xy)

sub_xy = x - y
print(sub_xy)

mul_x = x * 3
print(mul_x)

square_x = x ** 2
print(square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print(dot_vw)
print(dot_xv)
print(dot_xy)

concat_xy_rows = np.concatenate((x, y), axis=0)
print(concat_xy_rows)

concat_vw_cols = np.column_stack((v, w))
print(concat_vw_cols)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except Exception as e:
    print("Error:", e)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)
identity_check = A.dot(A_inv)
print(identity_check)


AB = A.dot(B)
BA = B.dot(A)

print("AB =\n", AB)
print("BA =\n", BA)

left_side = (A.dot(B)).T
right_side = B.T.dot(A.T)

print(left_side)
print(right_side)



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
A_sys = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]])

B_sys = np.array([-1, -3, 9])

A_inv_sys = np.linalg.inv(A_sys)
X_solution = A_inv_sys.dot(B_sys)

print("Solution:", X_solution)


Solution: [ 2.  1. -2.]


In [ ]:
X_linalg = np.linalg.solve(A_sys, B_sys)
print("Solution",X_linalg)


Solution [ 2.  1. -2.]
